/*
 * Sample Openapi Document 01
 * This is a sample yaml for yaml-doc-tool
 *
 * OpenAPI spec version: 1.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SampleResult
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-06T19:43:41.743004107Z[GMT]")

public class SampleResult {
    @SerializedName("id")
    private String id = null;

    @SerializedName("sampleTest")
    private String sampleTest = null;

    @SerializedName("myVeryLongSchemaNameExceedingLimit")
    private MyVeryLongSchemaNameExceedingLimit MyVeryLongSchemaNameExceedingLimit = null;

    @SerializedName("myVeryLongSchemaNameExceedingLimitV2")
    private MyVeryLongSchemaNameExceedingLimitV2 MyVeryLongSchemaNameExceedingLimitV2 = null;

    @SerializedName("sampleLevelTwoC")
    private SampleLevelTwoC sampleLevelTwoC = null;

    @SerializedName("sampleLevelTwoD")
    private SampleLevelTwoD sampleLevelTwoD = null;

    @SerializedName("sampleLevelTwoDAlt")
    private SampleLevelTwoD sampleLevelTwoDAlt = null;

    @SerializedName("sampleLevelTwoE")
    private SampleLevelTwoE sampleLevelTwoE = null;

    public SampleResult id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Id of the sample
     *
     * @return id
     **/
    @Schema(example = "1234", description = "Id of the sample")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public SampleResult sampleTest(String sampleTest) {
        this.sampleTest = sampleTest;
        return this;
    }

    /**
     * Sample properties
     *
     * @return sampleTest
     **/
    @Schema(example = "Sample text", description = "Sample properties")
    public String getSampleTest() {
        return sampleTest;
    }

    public void setSampleTest(String sampleTest) {
        this.sampleTest = sampleTest;
    }

    public SampleResult MyVeryLongSchemaNameExceedingLimit(
            MyVeryLongSchemaNameExceedingLimit MyVeryLongSchemaNameExceedingLimit) {
        this.MyVeryLongSchemaNameExceedingLimit = MyVeryLongSchemaNameExceedingLimit;
        return this;
    }

    /**
     * Get MyVeryLongSchemaNameExceedingLimit
     *
     * @return MyVeryLongSchemaNameExceedingLimit
     **/
    @Schema(description = "")
    public MyVeryLongSchemaNameExceedingLimit getMyVeryLongSchemaNameExceedingLimit() {
        return MyVeryLongSchemaNameExceedingLimit;
    }

    public void setMyVeryLongSchemaNameExceedingLimit(MyVeryLongSchemaNameExceedingLimit MyVeryLongSchemaNameExceedingLimit) {
        this.MyVeryLongSchemaNameExceedingLimit = MyVeryLongSchemaNameExceedingLimit;
    }

    public SampleResult MyVeryLongSchemaNameExceedingLimitV2(
            MyVeryLongSchemaNameExceedingLimitV2 MyVeryLongSchemaNameExceedingLimitV2) {
        this.MyVeryLongSchemaNameExceedingLimitV2 = MyVeryLongSchemaNameExceedingLimitV2;
        return this;
    }

    /**
     * Get MyVeryLongSchemaNameExceedingLimitV2
     *
     * @return MyVeryLongSchemaNameExceedingLimitV2
     **/
    @Schema(description = "")
    public MyVeryLongSchemaNameExceedingLimitV2 getMyVeryLongSchemaNameExceedingLimitV2() {
        return MyVeryLongSchemaNameExceedingLimitV2;
    }

    public void setMyVeryLongSchemaNameExceedingLimitV2(
            MyVeryLongSchemaNameExceedingLimitV2 MyVeryLongSchemaNameExceedingLimitV2) {
        this.MyVeryLongSchemaNameExceedingLimitV2 = MyVeryLongSchemaNameExceedingLimitV2;
    }

    public SampleResult sampleLevelTwoC(SampleLevelTwoC sampleLevelTwoC) {
        this.sampleLevelTwoC = sampleLevelTwoC;
        return this;
    }

    /**
     * Get sampleLevelTwoC
     *
     * @return sampleLevelTwoC
     **/
    @Schema(description = "")
    public SampleLevelTwoC getSampleLevelTwoC() {
        return sampleLevelTwoC;
    }

    public void setSampleLevelTwoC(SampleLevelTwoC sampleLevelTwoC) {
        this.sampleLevelTwoC = sampleLevelTwoC;
    }

    public SampleResult sampleLevelTwoD(SampleLevelTwoD sampleLevelTwoD) {
        this.sampleLevelTwoD = sampleLevelTwoD;
        return this;
    }

    /**
     * Get sampleLevelTwoD
     *
     * @return sampleLevelTwoD
     **/
    @Schema(description = "")
    public SampleLevelTwoD getSampleLevelTwoD() {
        return sampleLevelTwoD;
    }

    public void setSampleLevelTwoD(SampleLevelTwoD sampleLevelTwoD) {
        this.sampleLevelTwoD = sampleLevelTwoD;
    }

    public SampleResult sampleLevelTwoDAlt(SampleLevelTwoD sampleLevelTwoD) {
        this.sampleLevelTwoDAlt = sampleLevelTwoD;
        return this;
    }

    /**
     * Get sampleLevelTwoD
     *
     * @return sampleLevelTwoD
     **/
    @Schema(description = "")
    public SampleLevelTwoD getSampleLevelTwoDAlt() {
        return sampleLevelTwoDAlt;
    }

    public void setSampleLevelTwoDAlt(SampleLevelTwoD sampleLevelTwoD) {
        this.sampleLevelTwoDAlt = sampleLevelTwoD;
    }

    public SampleResult sampleLevelTwoE(SampleLevelTwoE sampleLevelTwoE) {
        this.sampleLevelTwoE = sampleLevelTwoE;
        return this;
    }

    /**
     * Get sampleLevelTwoE
     *
     * @return sampleLevelTwoE
     **/
    @Schema(description = "")
    public SampleLevelTwoE getSampleLevelTwoE() {
        return sampleLevelTwoE;
    }

    public void setSampleLevelTwoE(SampleLevelTwoE sampleLevelTwoE) {
        this.sampleLevelTwoE = sampleLevelTwoE;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SampleResult sampleResult = (SampleResult) o;
        return Objects.equals(this.id, sampleResult.id) && Objects.equals(this.sampleTest, sampleResult.sampleTest)
                && Objects.equals(this.MyVeryLongSchemaNameExceedingLimit, sampleResult.MyVeryLongSchemaNameExceedingLimit)
                && Objects.equals(this.MyVeryLongSchemaNameExceedingLimitV2, sampleResult.MyVeryLongSchemaNameExceedingLimitV2)
                && Objects.equals(this.sampleLevelTwoC, sampleResult.sampleLevelTwoC)
                && Objects.equals(this.sampleLevelTwoD, sampleResult.sampleLevelTwoD)
                && Objects.equals(this.sampleLevelTwoE, sampleResult.sampleLevelTwoE);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, sampleTest, MyVeryLongSchemaNameExceedingLimit, MyVeryLongSchemaNameExceedingLimitV2,
                sampleLevelTwoC, sampleLevelTwoD,
                sampleLevelTwoE);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SampleResult {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    sampleTest: ").append(toIndentedString(sampleTest)).append("\n");
        sb.append("    MyVeryLongSchemaNameExceedingLimit: ").append(toIndentedString(MyVeryLongSchemaNameExceedingLimit))
                .append("\n");
        sb.append("    MyVeryLongSchemaNameExceedingLimitV2: ").append(toIndentedString(MyVeryLongSchemaNameExceedingLimitV2))
                .append("\n");
        sb.append("    sampleLevelTwoC: ").append(toIndentedString(sampleLevelTwoC)).append("\n");
        sb.append("    sampleLevelTwoD: ").append(toIndentedString(sampleLevelTwoD)).append("\n");
        sb.append("    sampleLevelTwoE: ").append(toIndentedString(sampleLevelTwoE)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
